### ISSUE TITLE
Use suitable pictures for dashboard on the discount panel.

### ISSUE THREAD

**Issue by SamikaBhandari** [Prazeen7/Farm-Mart#5]
Use Suitable pictures for dashboard on discount panel.
![image](https://github.com/Prazeen7/Farm-Mart/assets/119203210/ac7ff619-1822-47e9-9851-8653798a6fe5)

**Comment by GaganKhadka** [comment]
Dear, @SamikaBhandari 

To improve the appeal and effectiveness of the discount panel on the dashboard, I have considered the following steps:

1. Use of High-Quality images
2. Consistent Branding
3. Highlight discounts
4. Engaging layout
5. Updating Content

Suggesting images,
![Fruits Veggies](https://github.com/Prazeen7/Farm-Mart/assets/119780387/6ec1cfc9-cdb6-4307-ab07-59a52598f5f8)
![Veggies2](https://github.com/Prazeen7/Farm-Mart/assets/119780387/4bfe99a0-a19d-4ee0-800b-4d60b0c8e7af)
