### ISSUE TITLE
Full page banner

### ISSUE THREAD

**Issue by ghost** [Prazeen7/Farm-Mart#9]
The first page should feature a full-page banner to provide clear navigation. 
As users scroll down, they should be directed to the second page, which will display a scrolling list of products.

**Comment by GaganKhadka** [comment]
Dear, @mingma888 

Thank you! for your consideration. To improve the full-page banner to provide clear navigation. As users scroll down, I have successfully fixed it, and the users first need to get registered and then sign up for our local farmers' market app. After all, they will be directed to the second page, which will display a scrolling list of products.

Login/SignUp Dashboard image,
![Login SignUp](https://github.com/Prazeen7/Farm-Mart/assets/119780387/04844d65-39a1-4e50-ab1b-0b22674db24f)
